version: "3"

services:
  db:
    container_name: bigglesaux-db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./itemdb:/var/lib/mysql
    env_file:
      - secrets.env
  app:
    build: ./server
    container_name: bigglesaux-server
    restart: always
    volumes:
      - ./server/scripts:/home/node/app/scripts
      - ./server/src:/home/node/app/src
    env_file:
      - secrets.env
    ports:
      - "3000:3000"
    command:
      "npm start"
  client:
    build: ./client
    container_name: bigglesaux-client
    restart: always
    volumes:
      - ./client/src:/home/node/app/src
    env_file:
      - secrets.env
    ports:
      - "8080:8080"
    command:
      "npm start"
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - client

volumes:
  static_volume:
