version: "3"

services:
  db:
    container_name: bigglesaux-db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./itemdb:/var/lib/postgresql/data
    env_file:
      - server.env
  app:
    build: .
    container_name: bigglesaux-server
    restart: always
    volumes:
      - ./scripts:/home/node/app/scripts
      - ./src:/home/node/app/src
    env_file:
      - server.env
    ports:
      - "3000:3000"
    command:
      "npm start"

volumes:
  static_volume:
