version: "3"

services:
  db:
    container_name: bigglesaux-db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./itemdb:/var/lib/mysql
    env_file:
      - db.env
  app:
    build: .
    container_name: bigglesaux-server
    restart: always
    volumes:
      - static_volume:/src/staticfiles
    env_file:
      - db.env
    environment:
        WAIT_HOSTS: db:5432
    ports:
      - "3000:3000"
    command:
      "npm start dev"
volumes:
  static_volume:
